### ISSUE TITLE
Uninstalling everything that was installed with the PremiumizerInstaller then reinstalling results in it now working

### ISSUE THREAD

**Issue by chest069** [neox387/PremiumizerInstaller#2]
Hello,
So I ran into this issue before. I am running windows 10 and have used the PremiumizerInstaller (latest ver). It will no longer start as a service once it is installed. Last time it was because I did the install manually then got it working by using the installer which caused everything to work. This is the only log I could find after doing the install. Thanks for any help.
There were changes to the main program so I don't know if that is the issue.
[Setup Log 2019-03-19 #003.txt](https://github.com/neox387/PremiumizerInstaller/files/2986092/Setup.Log.2019-03-19.003.txt)

**Comment by neox387** [comment]
if you uninstall it's bit fucked as it removed the whole premiumizer folder.
But for windows python and git are still installed.
so better to remove python and git first and then uninstall premiumizer before reinstall.

maybe try that first if the service starts then. Else try starting manually; in cmd for example
C:\Premiumizer\Python\python.exe C:\Premiumizer\Premiumizer\premiumizer\premiumizer.py

should give you an error is there is one..

**Comment by chest069** [comment]
Thanks I will try that. I was uninstalling git, python then premiumizer every time I was doing a new clean install so to speak. I will do it again and what you suggested and see what the error is.

This is what I got after uninstalling and reinstalling.
C:\Users\Chris Chester>C:\Premiumizer\Python\python.exe C:\Premiumizer\Premiumizer\premiumizer\premiumizer.py
Traceback (most recent call last):
  File "C:\Premiumizer\Premiumizer\premiumizer\premiumizer.py", line 25, in <module>
    import bencode
ModuleNotFoundError: No module named 'bencode'

**Comment by chest069** [comment]
![image](https://user-images.githubusercontent.com/661946/54756640-0cf91d00-4bbf-11e9-9839-ace51e8ce718.png)
 Hope fully you can see the picture I posted this is what I get when I try and enable the service. I have tried a reinstall 4 times same result and can't get past it.

**Comment by chest069** [comment]
This is my most recent install log file
[Setup Log 2019-03-21 #001.txt](https://github.com/neox387/PremiumizerInstaller/files/2992334/Setup.Log.2019-03-21.001.txt)

**Comment by neox387** [comment]
Mm I did a reinstall myself yesterday and all worked,

Try from cmd:

C:\Premiumizer\Python\python.exe C:\Premiumizer\Python\Scripts\pip3.exe install -r C:\Premiumizer\Premiumizer\requirements.txt

**Comment by neox387** [comment]
Installer does
C:\Premiumizer\Python\Scripts\pip3.exe install -r C:\Premiumizer\Premiumizer\requirements.txt

Without python path first maybe that's why it doesn't install the requirements for you mm

**Comment by chest069** [comment]
Ok so I don't know if this is progress but I get this error when running the command you listed from the command line.
`Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/neox387/myjdapi.git C:\Users\CHRISC~1\AppData\Local\Temp\pip-req-build-4l3i4h_2
Cannot find command 'git' - do you have 'git' installed and in your PATH?`
I have git installed
this is everything it said after I typed the command
`C:\Python27>C:\Premiumizer\Python\python.exe C:\Premiumizer\Python\Scripts\pip3.exe install -r C:\Premiumizer\Premiumizer\requirements.txt
Collecting git+https://github.com/neox387/myjdapi.git@tmp (from -r C:\Premiumizer\Premiumizer\requirements.txt (line 29))
  Cloning https://github.com/neox387/myjdapi.git (to revision tmp) to c:\users\chrisc~1\appdata\local\temp\pip-req-build-4l3i4h_2
  Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/neox387/myjdapi.git C:\Users\CHRISC~1\AppData\Local\Temp\pip-req-build-4l3i4h_2
Cannot find command 'git' - do you have 'git' installed and in your PATH?`

**Comment by neox387** [comment]
Python27 I see there that is also not right,

And the installer installs got to premiumizer/Git.

You probably have some conflicts wit python and Git.. 

Uninstall everything you see for python, Git, premiumizer in config panel 

Install again and see if you, get premiumizer/python and Git folders I would say..

**Comment by chest069** [comment]
Ok, I will do that. So which versions is it looking for exactly. I could install all of them manually.
Also I think that something happens (at least for me) when it tries to install pip. It flashes a warning in the command window then closes to quick for me to read it. I feel like somethings don't get installed maybe or it doesn't get added to the path. It seemed my last attempt gave me a lot more stuff installed but I did not use the installer.
I did install python then pip then git then premiumizer last time no installer file.
Thank you for the help on this.

**Comment by chest069** [comment]
Ok, update installing everything manually
Did this `virtualenv premiumizer\env` went ok
Did this next `env\Scripts\activate.bat`
got `The system cannot find the path specified.`

**Comment by neox387** [comment]
virtualenv isn't really needed

**Comment by neox387** [comment]
Just python 3 and Git

**Comment by neox387** [comment]
And for nzbToMedia to work pywin 32 but that should all work with installer..

**Comment by chest069** [comment]
Oh, ok just python 3 and git I grabbed this for pywin is it correct pywin32-218.win-amd64-py3.2.exe.

**Comment by neox387** [comment]
It's only for nzbToMedia so first try if you can, get premiumizer to work I think there is a newer version also its on in this Git project also..
https://github.com/neox387/PremiumizerInstaller/blob/master/utils/pywin32-224.win-amd64-py3.7.exe

**Comment by neox387** [comment]
Unless you use python 3.2 for some reason

**Comment by chest069** [comment]
Ok, so after uninstalling and then manually installing everything separate instead of using the premiumizer installer for Windows I have successfully got it all running again.
The only thing now is how do I get it to be a service again?
I really do appreciate the patience and help you provided. Anywhere I can donate money?

**Comment by neox387** [comment]
use Nssm
https://github.com/neox387/PremiumizerInstaller/blob/master/utils/nssm64.exe?raw=true

then open cmd as administrator and cd to where nssm64.exe is and put in:
nssm64.exe install Premiumizer C:\Premiumizer\Python\python.exe C:\Premiumizer\premiumizer\Premiumizer.py --windows
nssm64.exe set Premiumizer AppDirectory C:\Premiumizer\premiumizer
nssm64.exe set Premiumizer AppStopMethodSkip 6
nssm64.exe set Premiumizer AppStopMethodConsole 20000
nssm64.exe set Premiumizer AppRestartDelay 2000
nssm64.exe set Premiumizer AppEnvironmentExtra "PATH=C:\Premiumizer\Git\cmd;%PATH%" "PATH=C:\Premiumizer\Python;%PATH%"

I still don't get why the installer didn't work tough as this is the whole point so you don't have to do everything manually ..

**Comment by chest069** [comment]
Ok, Did what you said above. Got this when I tried to start it.
![image](https://user-images.githubusercontent.com/661946/54821744-835a5580-4c79-11e9-8b34-7a36286df778.png)

I had to do the following for the last line due to where git and python got installed when I did it manually.
`nssm64.exe set Premiumizer AppEnvironmentExtra "PATH=C:\Program Files\Git\cmd;%PATH%" "PATH=C:\Program Files\Python37\Python;%PATH%"`

Also this is what the service looks like when I open it. Is it supposed to be blank?
![image](https://user-images.githubusercontent.com/661946/54822881-6a06d880-4c7c-11e9-856f-651a86457dae.png)

I didn't get any errors doing your command but it comes back with then now when I try to enable the service.
![image](https://user-images.githubusercontent.com/661946/54822202-da145f00-4c7a-11e9-919d-f6ba01dff683.png)

So for now your command `python premiumizer.py` is the only thing that is making it work.

I don't know if it matters but the biggest thing I noticed during the automatic installer vs the manual installer is : it did not seem to install everything and if it did it was doing it in the wrong order maybe (i.e. if you don't have python and git already installed).

Also the auto installer put everything in "C:\Premiumizer" where as manual install put them in my user directory and in program files etc.

**Comment by neox387** [comment]
ye it can be blank.

with nssm64.exe edit Premiumizer you can view the settings.

this needs be the right paths tough it's just an example ..
nssm64.exe install Premiumizer C:\Premiumizer\Python\python.exe C:\Premiumizer\premiumizer\Premiumizer.py --windows

**Comment by neox387** [comment]
and yes installer will fuck up if you have git and python installed so thats why remove first =D

else install manually but then you should figure it out or know how git python nssm and stuff works

**Comment by neox387** [comment]
Mkay just tried installing again and something is indeed wrong =D

**Comment by neox387** [comment]
it installs correctly but does not do pip install -r requirements.txt right for some reason checking it

**Comment by chest069** [comment]
Yeah, I also remember seeing something about pip during install when when i was trying to figure out what wasn't getting installed.

That's good to know for me that it installs git and python right.

I got the service to work with what you said. :)

**Comment by neox387** [comment]
found out it was because of an error with git.

fixt on premiumizer requirements after PR

**Comment by neox387** [comment]
so if you are brave enough and delete everything xD the installer should now work again..

**Comment by chest069** [comment]
Ok, I might do that just to get everything into one place again. Is there a new installer or is it the same so I don't have to download it again?
Thanks again for everything.

**Comment by neox387** [comment]
Same installer normally it should complain if you had old one so v0.7 it latest

**Comment by chest069** [comment]
Ok, col. Thanks.
